// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqnukbqodqqmrwsggtcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbnVrYnFvZHFxbXJ3c2dndGN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzcxNDIsImV4cCI6MjA3MzY1MzE0Mn0.xxu_syL3evYMuGQ1f4Xa4NQ55CTlQyznrJ4yldgGmh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});